# Generated by Django 4.0.2 on 2022-02-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_bannerhero_bannerherotranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerhero',
            name='image',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
