# Generated by Django 4.0.2 on 2022-02-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_featureitem_featureitemtranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureitem',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
