# Generated by Django 4.0.2 on 2022-02-24 20:57

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_case_casetranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, size=[367, 400], upload_to='images/'),
        ),
    ]
