# Generated by Django 4.0.2 on 2022-02-24 22:34

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_teamexpert_socialaccount_teamexperttranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamexpert',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=100, size=[367, 400], upload_to='images/'),
        ),
    ]
