# Generated by Django 4.0.2 on 2022-02-25 11:57

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_socialaccount_team_expert'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, size=[367, 400], upload_to='images/')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProcessItemTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='website.processitem')),
            ],
            options={
                'verbose_name': 'process item Translation',
                'db_table': 'website_processitem_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
