# Generated by Django 4.0.2 on 2022-02-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_processitem_processitemtranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processitemtranslation',
            name='description',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='processitemtranslation',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
