# Generated by Django 4.0.2 on 2022-02-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_processitemtranslation_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processitem',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
