# Generated by Django 4.0.2 on 2022-02-25 15:04

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_content',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, size=[1920, 1280], upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_description',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, size=[550, 600], upload_to='images/'),
        ),
    ]
