# Generated by Django 4.0.2 on 2022-02-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_blogcategory_blog_blogtranslation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
