# Generated by Django 4.0.2 on 2022-02-28 09:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerhero',
            options={'verbose_name': 'Banner', 'verbose_name_plural': 'Banners'},
        ),
        migrations.AlterModelOptions(
            name='bannerherotranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Banner Translation'},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name': 'Blog category', 'verbose_name_plural': 'Blog categories'},
        ),
        migrations.AlterModelOptions(
            name='blogcategorytranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Blog category Translation'},
        ),
        migrations.AlterModelOptions(
            name='blogtranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Post Translation'},
        ),
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': 'Case', 'verbose_name_plural': 'Cases'},
        ),
        migrations.AlterModelOptions(
            name='casetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Case Translation'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='categorytranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Category Translation'},
        ),
        migrations.AlterModelOptions(
            name='choose',
            options={'verbose_name': 'Option', 'verbose_name_plural': 'Options'},
        ),
        migrations.AlterModelOptions(
            name='choosetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Option Translation'},
        ),
        migrations.AlterModelOptions(
            name='counter',
            options={'verbose_name': 'Counter', 'verbose_name_plural': 'Counters'},
        ),
        migrations.AlterModelOptions(
            name='countertranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Counter Translation'},
        ),
        migrations.AlterModelOptions(
            name='featureitem',
            options={'verbose_name': 'Feature item', 'verbose_name_plural': 'Feature items'},
        ),
        migrations.AlterModelOptions(
            name='featureitemtranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Feature item Translation'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedbacks'},
        ),
        migrations.AlterModelOptions(
            name='followlink',
            options={'verbose_name': 'Follow link', 'verbose_name_plural': 'Follow links'},
        ),
        migrations.AlterModelOptions(
            name='processitem',
            options={'verbose_name': 'Process item', 'verbose_name_plural': 'Process items'},
        ),
        migrations.AlterModelOptions(
            name='processitemtranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Process item Translation'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='producttranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Product Translation'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='servicetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Service Translation'},
        ),
        migrations.AlterModelOptions(
            name='socialaccount',
            options={'verbose_name': 'Social network', 'verbose_name_plural': 'Social networks'},
        ),
        migrations.AlterModelOptions(
            name='teamexpert',
            options={'verbose_name': 'Expert', 'verbose_name_plural': 'Experts'},
        ),
        migrations.AlterModelOptions(
            name='teamexperttranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Expert Translation'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonials'},
        ),
        migrations.AlterModelOptions(
            name='testimonialtranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Testimonial Translation'},
        ),
        migrations.AlterField(
            model_name='bannerhero',
            name='image',
            field=models.FileField(upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='bannerherotranslation',
            name='title1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title 1'),
        ),
        migrations.AlterField(
            model_name='bannerherotranslation',
            name='title2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title 2'),
        ),
        migrations.AlterField(
            model_name='bannerherotranslation',
            name='title3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title 3'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(max_length=100, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='website.blogcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date and time'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_content',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, size=[1920, 1280], upload_to='images/', verbose_name='Main image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_description',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, size=[550, 600], upload_to='images/', verbose_name='Thumbnail image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(verbose_name='Short url'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(verbose_name='Short url'),
        ),
        migrations.AlterField(
            model_name='blogcategorytranslation',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='blogtranslation',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='blogtranslation',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='case',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, size=[367, 400], upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='case',
            name='slug',
            field=models.SlugField(verbose_name='Short url'),
        ),
        migrations.AlterField(
            model_name='casetranslation',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='casetranslation',
            name='title',
            field=models.CharField(max_length=15, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='website.category', verbose_name='Parent category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(verbose_name='Short url'),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='choose',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Icon file'),
        ),
        migrations.AlterField(
            model_name='choose',
            name='icon_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Font Awesome Icon'),
        ),
        migrations.AlterField(
            model_name='choosetranslation',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='choosetranslation',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='count',
            field=models.IntegerField(verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Icon file'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='icon_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Font Awesome Icon'),
        ),
        migrations.AlterField(
            model_name='countertranslation',
            name='title',
            field=models.CharField(max_length=15, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='featureitem',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Icon file'),
        ),
        migrations.AlterField(
            model_name='featureitem',
            name='icon_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Font Awesome Icon'),
        ),
        migrations.AlterField(
            model_name='featureitem',
            name='slug',
            field=models.SlugField(verbose_name='Short url'),
        ),
        migrations.AlterField(
            model_name='featureitemtranslation',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='featureitemtranslation',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Fullname'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='followlink',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Icon file'),
        ),
        migrations.AlterField(
            model_name='followlink',
            name='icon_text',
            field=models.TextField(blank=True, null=True, verbose_name='Font Awesome Icon'),
        ),
        migrations.AlterField(
            model_name='followlink',
            name='link',
            field=models.TextField(verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='processitem',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, size=[100, 100], upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='processitemtranslation',
            name='description',
            field=models.CharField(max_length=70, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='processitemtranslation',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_content',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, size=[1920, 1280], upload_to='images/', verbose_name='Main image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_description',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, size=[550, 600], upload_to='images/', verbose_name='Thumbnail image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(verbose_name='Short url'),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='description',
            field=models.TextField(verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Icon file'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Font Awesome Icon'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(verbose_name='Short url'),
        ),
        migrations.AlterField(
            model_name='servicetranslation',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='servicetranslation',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='servicetranslation',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Icon file'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='icon_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Font Awesome Icon'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='link',
            field=models.TextField(verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='team_expert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='website.teamexpert', verbose_name='Expert'),
        ),
        migrations.AlterField(
            model_name='teamexpert',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=100, size=[367, 400], upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='teamexpert',
            name='slug',
            field=models.SlugField(verbose_name='Short url'),
        ),
        migrations.AlterField(
            model_name='teamexperttranslation',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='teamexperttranslation',
            name='job',
            field=models.CharField(max_length=255, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='teamexperttranslation',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='fullname',
            field=models.CharField(max_length=30, verbose_name='Fullname'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, size=[100, 100], upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MaxLengthValidator, django.core.validators.MinLengthValidator], verbose_name='Rating score'),
        ),
        migrations.AlterField(
            model_name='testimonialtranslation',
            name='comment',
            field=models.CharField(max_length=70, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='testimonialtranslation',
            name='identity',
            field=models.CharField(max_length=70, verbose_name='Commenter'),
        ),
    ]
