# Generated by Django 4.0.2 on 2022-02-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_staticpage_staticpagetranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
